### ISSUE TITLE
不用arduino，可以实现吗

### ISSUE THREAD

**Issue by 123xinshou** [shuai132/BalanceCar#4]
不用arduino，可以实现吗

**Comment by shuai132** [comment]
是安卓（Android），这个用的是STM32F4不是Arduino。

**Comment by 123xinshou** [comment]
ok




.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shuai132/BalanceCar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月23日(星期五) 下午5:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shuai132/BalanceCar] 不用arduino，可以实现吗 (Issue #4)





 
是安卓（Android），这个用的是STM32F4不是Arduino。
